os: windows
language: csharp
mono: none

install:
 - choco install dotnetcore-sdk
 - dotnet restore
script:
 - dotnet build ./MintPlayer.BrowserDialog/MintPlayer.BrowserDialog.csproj --configuration Release
